# Generated by Django 2.2.2 on 2019-06-17 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long')])),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='social.User')),
            ],
        ),
    ]
